### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by LaBestiaBrutal** [infernalexp/Nekos-Enchanted-Books#16]
Trying to use mod on a 1.18.1 server, crashes at startup

Crash rep:

[crash-2022-04-15_19.03.28-fml.txt](https://github.com/infernalexp/Nekos-Enchanted-Books/files/8499023/crash-2022-04-15_19.03.28-fml.txt)
.

**Comment by SwanX1** [comment]
This is a client-side mod, don't use it on the server.

**Comment by TheDeviantCrafter** [comment]
Could the mod be configured to disable itself when run on a dedicated server? Creating a server by copying the mods folder from a single player instance is pretty common practice.
