### ISSUE TITLE
Textures aren't visible

### ISSUE THREAD

**Issue by WarmIceCream** [infernalexp/Nekos-Enchanted-Books#19]
Even with no resource packs enabled, all enchanted books are using their default look. I thought it could be a mod incompatibility, though considering my mods and how many there are, I'm not sure which could be the culprit

NEB 1.7.0
Forge 40.1.0
MC 1.18.2
[latest.log](https://github.com/infernalexp/Nekos-Enchanted-Books/files/8696372/latest.log)

**Comment by nekomaster1000** [comment]
It probably is a mod incompatibility. This isn't really something we can help with with such a vague description.

**Comment by WarmIceCream** [comment]
I'll attach the full mod list for my modpack if it's any help - are there any known mod incompatibilities?
[list.txt](https://github.com/infernalexp/Nekos-Enchanted-Books/files/8696399/list.txt)

**Comment by WarmIceCream** [comment]
turns out it was a video setting. not sure if it was a vanilla one, or an optifine one but I narrowed it down that far. 

seemed to be also affecting other visual mods like better foliage, but all works fine now that I reset the settings to default
